export type Variation = {
  id: string;
  label: string;
  price: number;
  maxQty: number;
};

export type Item = {
  id: string;
  name: string;

  // ✅ optionalにする
  maxQty?: number;
  price?: number;
  description?: string;
  size?: string;
  note?: string;

  imageUrl?: string;
  variations?: Variation[];
};

export const internalItems: Item[] = [
  {
    id: "1pa",
    name: "一面パーテーション",
    maxQty: 5,
    price: 0,
    description: "展示や仕切りで使用できます。",
    size: "横幅：100cm\n高さ：150cmまたは160cmまたは180cm",
    note: "屋内でのみ使用可能です。",
    imageUrl: "/items/1pa.jpg",
  },
  {
    id: "2pa",
    name: "二面パーテーション",
    maxQty: 9,
    price: 0,
    description: "展示や仕切りで使用できます。",
    size: "横幅：210cm\n高さ：150cm",
    note:"屋内でのみ使用可能です。",
    imageUrl: "/items/2pa.jpg",
  },
  {
    id: "3pa",
    name: "三面パーテーション",
    maxQty: 1,
    price: 0,
    description: "展示や仕切りで使用できます。",
    size: "横幅：300cm\n高さ：150cm",
    note:"屋内でのみ使用可能です。",
    imageUrl: "/items/3pa.jpg",
  },
  {
    id: "tpa",
    name: "テープパーテーション",
    maxQty: 17,
    price: 0,
    description: "仕切りや列整理で使用できます。",
    size: "長さ170cm",
    note:"赤3個、青7個、特殊青7個",
    imageUrl: "/items/tpa.jpg",
  },
  {
    id: "a3fsw",
    name: "A3立て看板(白)",
    maxQty: 11,
    price: 0,
    description: "通行人への周知等で使用できます。",
    size: "高さ：115cm",
    note: "特になし",
    imageUrl: "/items/a3fsw.jpg",
  },
  {
    id: "a3fsb",
    name: "A3立て看板(黒)",
    maxQty: 10,
    price: 0,
    description: "通行人への周知等で使用できます。",
    size: "高さ：110cmまたは121cm",
    note: "特になし",
    imageUrl: "/items/a3fsb.jpg",
  },
  {
    id: "a3fsg",
    name: "A3立て看板(灰)",
    maxQty: 4,
    price: 0,
    description: "通行人への周知等で使用できます。",
    size: "高さ：120cm",
    note: "特になし",
    imageUrl: "/items/a3fsg.jpg",
  },
  {
    id: "ps",
    name: "ポップスタンド",
    maxQty: 4,
    price: 0,
    description: "通行人への周知等で使用できます。",
    size: "高さ：140cm~230cm",
    note: "特になし",
    imageUrl: "/items/ps.jpg",
  },
  {
    id: "a1ssb",
    name: "A1サインスタンド(両面)",
    maxQty: 16,
    price: 0,
    description: "ポスターの展示等で使用できます。",
    size: "横幅：65cm\n高さ：120cm",
    note: "特になし",
    imageUrl: "/items/a1ssb.jpg",
  },
  {
    id: "a1sso",
    name: "A1サインスタンド(片面)",
    maxQty: 10,
    price: 0,
    description: "ポスターの展示等で使用できます。",
    size: "横幅：60cm\n高さ：120cm",
    note: "特になし",
    imageUrl: "/items/a1sso.jpg",
  },
  {
    id: "ea",
    name: "イーゼル",
    maxQty: 75,
    price: 0,
    description: "パネル展示等で使用できます。",
    size: "横幅：45cm\n高さ：95cm~165cm",
    note: "特になし",
    imageUrl: "/items/ea.jpg",
  },
  {
    id: "bf",
    name: "のぼり",
    maxQty: 9,
    price: 0,
    description: "旗の掲示等で使用できます。",
    size: "高さ：165cm~230cm",
    note: "おもり・ポールのセットです。",
    imageUrl: "/items/bf.jpg",
  },
  {
    id: "ld",
    name: "長机",
    maxQty: 80,
    price: 0,
    description: "受付や展示等で使用できます。",
    size: "横幅：150cm\n奥行：45cm\n高さ：70cm",
    note: "模擬店企画には4台配布されます。",
    imageUrl: "/items/ld.jpg",
  },
  {
    id: "pchair",
    name: "パイプ椅子",
    maxQty: 500,
    price: 0,
    description: "椅子として使用できます。",
    size: "横幅：50cm",
    note: "模擬店企画には4脚配布されます。",
    imageUrl: "/items/pchair.jpg",
  },
  {
    id: "reel",
    name: "ドラムリール",
    maxQty: 5,
    price: 0,
    description: "電源の接続に使用できます。",
    size: "長さ20m~30m",
    note: "色・メーカー等は種類によって異なります。",
    imageUrl: "/items/reel.jpg",
  },
  {
    id: "cc",
    name: "カラーコーン",
    maxQty: 50,
    price: 0,
    description: "列整備等で使用できます。",
    size: "高さ：70cm",
    note: "各テントに4個配布されます。",
    imageUrl: "/items/cc.jpg",
  },
  {
    id: "cb",
    name: "コーンバー",
    maxQty: 50,
    price: 0,
    description: "列整備等で使用できます。",
    size: "長さ：150cm",
    note: "各テントに3本配布されます。",
    imageUrl: "/items/cb.jpg",
  },
];

export const externalItems: Item[] = [
  {
    id: "teppan",
    name: "LP鉄板焼",
    maxQty: 2,
    price: 5940,
    description: "鉄板系の調理で使用できます。",
    size: "横幅：60cm\n奥行：55cm\n高さ：18cm",
    note: "ガスはついておりません。ガスも登録してください。",
    imageUrl: "/items/teppan.jpg",
  },
  {
    id: "takoyaki",
    name: "LPタコ焼機",
    maxQty: 2,
    price: 5940,
    description: "たこ焼き等の調理で使用できます。",
    size: "高さ：51cm\n奥行：26cm\n高さ：18cm",
    note: "ガスはついておりません。ガスも登録してください。千枚通し・粉つきがついています。",
    imageUrl: "/items/takoyaki.jpg",
  },
  {
    id: "crepe",
    name: "LPクレープ焼機",
    maxQty: 2,
    price: 5940,
    description: "クレープ等の調理で使用できます。",
    size: "横幅：55cm\n奥行：45cm\n高さ：23cm",
    note: "ガスはついておりません。ガスも登録してください。クレープ用トンボ・スパチュラがついています。",
    imageUrl: "/items/crepe.jpg",
  },
  {
    id: "obanyaki",
    name: "LP大判焼き機",
    maxQty: 2,
    price: 9900,
    description: "大判焼き等の調理で使用できます。",
    size: "横幅：68cm\n奥行：57cm\n高さ：28cm",
    note: "ガスはついておりません。ガスも登録してください。あんさし・ヘラ・生地落としがついています。",
    imageUrl: "/items/obanyaki.jpg",
  },
  {
    id: "yakitori",
    name: "LP焼鳥機",
    maxQty: 4,
    price: 4950,
    description: "焼き鳥等の調理で使用できます。",
    size: "横幅：60cm\n奥行：14cm\n高さ：15cm",
    note: "ガスはついておりません。ガスも登録してください。",
    imageUrl: "/items/yakitori.jpg",
  },
  {
    id: "yakidai",
    name: "LP焼台四本パイプ",
    maxQty: 4,
    price: 4950,
    description: "焼きトウモロコシ等の調理で使用できます。",
    size: "横幅：45cm\n奥行：23cm\n高さ：19cm",
    note: "ガスはついておりません。ガスも登録してください。焼き網がついています。",
    imageUrl: "/items/yakidai.jpg",
  },
  {
    id: "flyer",
    name: "LP卓上フライヤー",
    maxQty: 2,
    price: 11880,
    description: "揚げ物の調理で使用できます。",
    size: "横幅：40cm\n奥行：50cm\n高さ：40cm",
    note: "ガスはついておりません。ガスも登録してください。かす取りがついています。",
    imageUrl: "/items/flyer.jpg",
  },
  {
    id: "steamer",
    name: "セイロセット",
    maxQty: 2,
    price: 7200,
    description: "蒸し調理で使用できます。",
    size: "2升2段",
    note: "ガスはついておりません。ガスも登録してください。",
    imageUrl: "/items/steamer.jpg",
  },
  {
    id: "gasstove",
    name: "LPガス台",
    description: "加熱作業に使用できます。",
    size: "二重(横幅：33cm/奥行：51cm/高さ：12cm)\n三重(横幅：44cm/奥行：69cm/高さ：16cm)",
    note: "ガスはついておりません。ガスも登録してください。画像は三重です。",
    imageUrl: "/items/gasstove.jpg",
    variations: [
      {
      id: "gasstove2",
      label: "二重",
      price: 2475,
      maxQty: 2,
      },
      {
      id: "gasstove3",
      label: "三重",
      price: 3960,
      maxQty: 2,
      },
    ],
  },
  {
    id: "popcorn",
    name: "ポップコーン機",
    maxQty: 2,
    price: 11880,
    description: "ポップコーンの調理に使用できます。",
    size: "横幅：45cm\n奥行：35cm\n高さ：63cm",
    note: "塩味のみ調理可能です。",
    imageUrl: "/items/popcorn.jpg",
  },
  {
    id: "cottoncandy",
    name: "電気綿菓子機",
    maxQty: 2,
    price: 11880,
    description: "綿菓子の調理に使用できます。",
    size: "横幅：64cm\n奥行：64cm\n高さ：83cm",
    note: "特になし",
    imageUrl: "/items/cottoncandy.jpg",
  },
  {
    id: "warmer",
    name: "保温機",
    maxQty: 2,
    price: 4950,
    description: "提供品の保温に使用できます。",
    size: "横幅：45cm\n奥行：30cm\n高さ：50cm",
    note: "特になし",
    imageUrl: "/items/warmer.jpg",
  },
  {
    id: "mkakigori",
    name: "手動かき氷機",
    maxQty: 2,
    price: 4950,
    description: "かき氷の調理で使用できます。",
    size: "横幅：39cm\n奥行：27cm\n高さ：58cm",
    note: "ブロック氷のみ使用できます。",
    imageUrl: "/items/mkakigori.jpg",
  },
  {
    id: "akakigori",
    name: "電動かき氷機",
    maxQty: 2,
    price: 10890,
    description: "かき氷の調理で使用できます。",
    size: "横幅：31cm\n奥行：40cm\n高さ：58cm",
    note: "ブロック氷のみ使用できます。",
    imageUrl: "/items/akakigori.jpg",
  },
  {
    id: "juicedispenser",
    name: "ジュースディスペンサー",
    maxQty: 5,
    price: 14850,
    description: "ジュースの冷却に使用できます。",
    size: "横幅：32cm\n奥行：43cm\n高さ：57cm",
    note: "3~7℃で温度調節を行えます。",
    imageUrl: "/items/juicedispenser.jpg",
  },
  {
    id: "nabe",
    name: "鍋",
    description: "ゆでる調理等で使用できます。",
    size: "直径30cm\n直径39cm",
    note: "IHに対応しておりません。",
    imageUrl: "/items/nabe.jpg",
    variations: [
      {
      id: "nabe30",
      label: "30cm",
      price: 990,
      maxQty: 4,
      },
      {
      id: "nabe39",
      label: "39cm",
      price: 1485,
      maxQty: 4,
      },
    ],
  },
  {
    id: "snabe",
    name: "寸動鍋",
    description: "ゆでる調理等で使用できます。",
    size: "46L~161L",
    note: "IHには対応しておりません。",
    imageUrl: "/items/snabe.jpg",
    variations: [
      {
      id: "snabe46",
      label: "46L",
      price: 2970,
      maxQty: 4,
      },
      {
      id: "snabe86",
      label: "86L",
      price: 4950,
      maxQty: 4,
      },
      {
      id: "snabe161",
      label: "161L",
      price: 9900,
      maxQty: 4,
      },
    ],
  },
  {
    id: "ib",
    name: "アイスボックス",
    description: "食品の冷蔵保存等で使用できます。",
    size: "45L~120L",
    note: "特になし",
    imageUrl: "/items/ib.jpg",
    variations: [
      {
      id: "ib45",
      label: "45L",
      price: 3465,
      maxQty: 1,
      },
      {
      id: "ib64",
      label: "64L",
      price: 4950,
      maxQty: 1,
      },
      {
      id: "ib90",
      label: "90L",
      price: 7920,
      maxQty: 1,
      },
      {
      id: "ib120",
      label: "120L",
      price: 11880,
      maxQty: 1,
      },
    ],
  },
  {
    id: "suisoenniti",
    name: "縁日用水槽",
    maxQty: 2,
    price: 3960,
    description: "ヨーヨー釣り等で使用できます。",
    size: "横幅：121cm\n奥行：71cm\n高さ：25cm",
    note: "特になし",
    imageUrl: "/items/suisoenniti.jpg",
  },
  {
    id: "suiso",
    name: "ドブヅケ水槽",
    maxQty: 2,
    price: 4950,
    description: "ペットボトルの販売等で使用できます。",
    size: "横幅：76cm\n奥行：45cm\n高さ：78cm",
    note: "107Lです。",
    imageUrl: "/items/suiso.jpg",
  },
  {
    id: "sl",
    name: "脚立",
    description: "高所作業で使用できます。",
    size: "高さ120cm~270cm",
    note: "高所作業時には、必ずヘルメットを着用してください。画像は120cmと270cmです。",
    imageUrl: "/items/sl.jpg",
    variations: [
      {
      id: "sl120",
      label: "120cm",
      price: 990,
      maxQty: 5,
      },
      {
      id: "sl210",
      label: "210cm",
      price: 1980,
      maxQty: 5,
      },
      {
      id: "sl270",
      label: "270cm",
      price: 2970,
      maxQty: 5,
      },
    ],
  },
];

  //↓これをコピペ
  /*{
    id: "",
    name: "",
    maxQty: 0,
    price: 0,
    description: "",
    size: "横幅：cm\n奥行：cm\n高さ：cm",
    note: "",
    imageUrl: "/items/.jpg",
  },*/

  /*{
    id: "",
    name: "",
    description: "",
    size: "",
    note: "",
    imageUrl: "/items/.jpg",
    variations: [
      {
      id: "",
      label: "",
      price: 60,
      maxQty: 0,
      },
      {
      id: "",
      label: "",
      price: 0,
      maxQty: 0,
      },
    ],
  },*/

//git add lib/items.ts public/items/.jpg
//git commit -m "add item list"
//git push

//update
